# Generated by Django 4.0.1 on 2022-08-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_task', models.CharField(max_length=50)),
                ('check_task', models.BooleanField(default=False)),
            ],
        ),
    ]
